---
title: "SupplementaryFig3"
author: "Tülay Karakulak"
date: "2024-03-15"
output: html_document
---

```{r libraries}
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
library(knitr)
library(rmarkdown)
library(harmony)
library(Matrix)
library(cowplot)
library(RColorBrewer)
library(viridis)
library(ggpubr)
theme_set(theme_cowplot())
set.seed(12345)
```

```{r uploadAnnotation}
isoform_annotations_normal <- read.csv('/Users/tulaykarakulak/Documents/GitHub/ccRCC_scLongRead/InputFiles/Normal/scisoseq_classification.filtered_lite_classification.txt', header = TRUE, sep='\t')
# ccRCC_2
isoform_annotations_ccRCC_2 <- read.csv('/Users/tulaykarakulak/Documents/GitHub/ccRCC_scLongRead/InputFiles/ccRCC2/scisoseq_classification.filtered_lite_classification.txt', header = TRUE, sep='\t')
# ccRCC_3
isoform_annotations_ccRCC_3 <- read.csv('/Users/tulaykarakulak/Documents/GitHub/ccRCC_scLongRead/InputFiles/ccRCC3/scisoseq_classification.filtered_lite_classification.txt', header = TRUE, sep='\t')

isoform_annotations_ccRCC_4 <- read.csv('/Users/tulaykarakulak/Documents/GitHub/ccRCC_scLongRead/InputFiles/ccRCC4/scisoseq_classification.filtered_lite_classification.txt', header = TRUE, sep='\t')

isoform_annotations_ccRCC_5 <- read.csv('/Users/tulaykarakulak/Documents/GitHub/ccRCC_scLongRead/InputFiles/ccRCC5/scisoseq_classification.filtered_lite_classification.txt', header = TRUE, sep='\t')
```


```{r ensemblNumberOfTranscripts}
ensembl_ensg_enst <- read.csv('/Users/tulaykarakulak/Documents/PhD/Projects/ccRCC_Sc_lrSequencing/070923_Final/ensembl/ensg_enst_geneName_Exon.txt', header = TRUE, sep='\t')
```


```{r count_Isoforms_Ensembl}
Iso_Ensembl <- ensembl_ensg_enst %>% dplyr::select(Gene.stable.ID, Gene.name, Transcript.stable.ID) %>% dplyr::distinct() %>% group_by(Gene.stable.ID, Gene.name) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))
head(Iso_Ensembl)


Iso_Ensembl_exon <- ensembl_ensg_enst %>% dplyr::select(Gene.stable.ID, Gene.name, Exon.stable.ID) %>% dplyr::distinct() %>% group_by(Gene.stable.ID, Gene.name) %>% summarise(ExonCount = n()) %>% dplyr::arrange(desc(ExonCount))
head(Iso_Ensembl_exon)
```

```{r count_Isoform_LR}
# Novel Isoform Counts
IsoCount_isoform_annotations_normal <- isoform_annotations_normal %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('novel_in_catalog', 'novel_not_in_catalog')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))

IsoCount_isoform_annotations_ccRCC2 <- isoform_annotations_ccRCC_2 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('novel_in_catalog', 'novel_not_in_catalog')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC3 <- isoform_annotations_ccRCC_3 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('novel_in_catalog', 'novel_not_in_catalog')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC4 <- isoform_annotations_ccRCC_4 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('novel_in_catalog', 'novel_not_in_catalog')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC5 <- isoform_annotations_ccRCC_5 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('novel_in_catalog', 'novel_not_in_catalog')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


## Incomplete Splice Match 
IsoCount_isoform_annotations_normal_ISM <- isoform_annotations_normal %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('incomplete-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC2_ISM <- isoform_annotations_ccRCC_2 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('incomplete-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC3_ISM <- isoform_annotations_ccRCC_3 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('incomplete-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC4_ISM <- isoform_annotations_ccRCC_4 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('incomplete-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC5_ISM <- isoform_annotations_ccRCC_5 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('incomplete-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


## Full Splice Match 
IsoCount_isoform_annotations_normal_FSM <- isoform_annotations_normal %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('full-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC2_FSM <- isoform_annotations_ccRCC_2 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('full-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC3_FSM <- isoform_annotations_ccRCC_3 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('full-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC4_FSM <- isoform_annotations_ccRCC_4 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('full-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))


IsoCount_isoform_annotations_ccRCC5_FSM <- isoform_annotations_ccRCC_5 %>% dplyr::select(isoform, structural_category, associated_gene) %>% dplyr::filter(structural_category %in% c('full-splice_match')) %>% dplyr::distinct() %>% group_by(associated_gene) %>% summarise(IsoCount = n()) %>% dplyr::arrange(desc(IsoCount))
```


```{r merge_files}
# Novel Isoforms Transcript Counts
colnames(Iso_Ensembl) <- c('ENSG', 'associated_gene', 'IsoCount')
IsoCount_isoform_annotations_normal_Ensembl <- merge(Iso_Ensembl, IsoCount_isoform_annotations_normal, by='associated_gene')

IsoCount_isoform_annotations_ccRCC2_Ensembl <- merge(Iso_Ensembl, IsoCount_isoform_annotations_ccRCC2, by='associated_gene')

IsoCount_isoform_annotations_ccRCC3_Ensembl <- merge(Iso_Ensembl, IsoCount_isoform_annotations_ccRCC3, by='associated_gene')

IsoCount_isoform_annotations_ccRCC4_Ensembl <- merge(Iso_Ensembl, IsoCount_isoform_annotations_ccRCC4, by='associated_gene')

IsoCount_isoform_annotations_ccRCC5_Ensembl <- merge(Iso_Ensembl, IsoCount_isoform_annotations_ccRCC5, by='associated_gene')

# Novel Isoform vs exon counts
colnames(Iso_Ensembl_exon) <- c('ENSG', 'associated_gene', 'IsoCount')
IsoCount_isoform_annotations_normal_Ensembl_exon <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_normal, by='associated_gene')

IsoCount_isoform_annotations_ccRCC2_Ensembl_exon <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC2, by='associated_gene')

IsoCount_isoform_annotations_ccRCC3_Ensembl_exon <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC3, by='associated_gene')

IsoCount_isoform_annotations_ccRCC4_Ensembl_exon <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC4, by='associated_gene')

IsoCount_isoform_annotations_ccRCC5_Ensembl_exon <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC5, by='associated_gene')


# ISM vs Exon Count
# exon count
IsoCount_isoform_annotations_normal_Ensembl_exon_ISM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_normal_ISM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC2_ISM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC3_ISM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC4_ISM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC5_ISM, by='associated_gene')


## FSM vs Exon Counts
IsoCount_isoform_annotations_normal_Ensembl_exon_FSM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_normal_FSM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC2_FSM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC3_FSM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC4_FSM, by='associated_gene')

IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM <- merge(Iso_Ensembl_exon, IsoCount_isoform_annotations_ccRCC5_FSM, by='associated_gene')
```


```{r plotCorrelationExonNovelIsoform}
# Exon Number - Novel Isoform Correlation
## Normal
IsoCount_isoform_annotations_normal_Ensembl_exon$log2.x <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon$IsoCount.x)
IsoCount_isoform_annotations_normal_Ensembl_exon$log2.y <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon$IsoCount.y)
IsoCount_isoform_annotations_normal_Ensembl_exon$Group <- 'Normal'


## ccRCC2
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon$log2.x <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon$IsoCount.x)
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon$log2.y <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon$IsoCount.y)
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon$Group <- 'ccRCC2'


## ccRCC3
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon$log2.x <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon$IsoCount.x)
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon$log2.y <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon$IsoCount.y)
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon$Group <- 'ccRCC3'


## ccRCC4
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon$log2.x <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon$IsoCount.x)
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon$log2.y <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon$IsoCount.y)
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon$Group <- 'ccRCC4'

## ccRCC5
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon$log2.x <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon$IsoCount.x)
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon$log2.y <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon$IsoCount.y)
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon$Group <- 'ccRCC5'

NovelIsoform_Exons <- rbind(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon, IsoCount_isoform_annotations_ccRCC4_Ensembl_exon,
      IsoCount_isoform_annotations_ccRCC3_Ensembl_exon, IsoCount_isoform_annotations_ccRCC2_Ensembl_exon, 
      IsoCount_isoform_annotations_normal_Ensembl_exon)

NovelIsoform_Exons_plot <- ggscatter(NovelIsoform_Exons, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#Novel Isoform", ylab = "#Ensembl Exon", size=0.5) + facet_wrap(~Group)

NovelIsoform_Exons_plot

ggsave("Supplementary_Fig3A.png", plot = NovelIsoform_Exons_plot, bg = "transparent", width = 12, height = 5)
```


```{r ISMCorrelation}
# Exon Number - ISM Correlation
## Normal
IsoCount_isoform_annotations_normal_Ensembl_exon_ISM$log2.x <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon_ISM$IsoCount.x)
IsoCount_isoform_annotations_normal_Ensembl_exon_ISM$log2.y <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon_ISM$IsoCount.y)
IsoCount_isoform_annotations_normal_Ensembl_exon_ISM$Group <- 'Normal'


## ccRCC2
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM$IsoCount.y)
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM$Group <- 'ccRCC2'

## ccRCC3
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM$IsoCount.y)
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM$Group <- 'ccRCC3'


## ccRCC4
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM$IsoCount.y)
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM$Group <- 'ccRCC4'


## ccRCC5
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM$IsoCount.y)
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM$Group <- 'ccRCC5'


ISMIsoform_Exons <- rbind(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_ISM, IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_ISM,
      IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_ISM, IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_ISM, 
      IsoCount_isoform_annotations_normal_Ensembl_exon_ISM)

ISMIsoform_Exons_plot <- ggscatter(ISMIsoform_Exons, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#ISM Isoform", ylab = "#Ensembl Exon", size=0.5) + facet_wrap(~Group)

ggsave("Supplementary_Fig3B.png", plot = ISMIsoform_Exons_plot, bg = "transparent", width = 12, height = 5)
```



```{r FSMCorrelation}
# Exon Number - FSM Correlation
## Normal
IsoCount_isoform_annotations_normal_Ensembl_exon_FSM$log2.x <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon_FSM$IsoCount.x)
IsoCount_isoform_annotations_normal_Ensembl_exon_FSM$log2.y <- log2(IsoCount_isoform_annotations_normal_Ensembl_exon_FSM$IsoCount.y)

ggscatter(IsoCount_isoform_annotations_normal_Ensembl_exon_FSM, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#LR FSM Isoform", ylab = "#Ensembl Exon")

## ccRCC2
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM$IsoCount.y)

ggscatter(IsoCount_isoform_annotations_ccRCC2_Ensembl_exon_FSM, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#LR FSM Isoform", ylab = "#Ensembl Exon")

## ccRCC3
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM$IsoCount.y)

ggscatter(IsoCount_isoform_annotations_ccRCC3_Ensembl_exon_FSM, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#LR FSM Isoform", ylab = "#Ensembl Exon")

## ccRCC4
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM$IsoCount.y)

ggscatter(IsoCount_isoform_annotations_ccRCC4_Ensembl_exon_FSM, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#LR FSM Isoform", ylab = "#Ensembl Exon")


## ccRCC5
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM$log2.x <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM$IsoCount.x)
IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM$log2.y <- log2(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM$IsoCount.y)

ggscatter(IsoCount_isoform_annotations_ccRCC5_Ensembl_exon_FSM, x = "log2.y", y = "log2.x", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "pearson",
           xlab = "#LR FSM Isoform", ylab = "#Ensembl Exon")


```

